name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/pre-commit@v2.0.16

  #deptry:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/deptry@main
  #      with:
  #        source-folder: 'pyamber'
